### ISSUE TITLE
好想考過哦 QQ

### ISSUE THREAD

**Issue by aesophor** [setsal/GPE-Helper#1]
<img width="236" alt="Screen Shot 2021-03-10 at 10 50 48 AM" src="https://user-images.githubusercontent.com/32998585/110568760-7f89ab80-818e-11eb-843b-e6a7541dd17b.png">

**Comment by setsal** [comment]
你行的

![](https://media.giphy.com/media/621nhiYcf5pWS8yfmT/giphy.gif)

**Comment by aesophor** [comment]
幹終於過了！！！！！！！好穩
